language: node_js
node_js:
  - "5"
  - "4"
notifications:
  slack:
    rooms:
      secure: EflcRyuXWBXsVWlGmk8fgjFhxMFXgNMiQwy0pQxnj+lzEFYIfJ9RfCZapchTnC5FxcmnjoNgf/GFjWkV82DUiPlGhsPoCsOIvjO6XTjHBLKcRYzBLZFPz0J6WjvTcVwEuNEUSNUjIGkgGDfxW61PNY1uIiZv8XgYKs597bMdSiU=
